name: structure
version: 1.0.0
description: Made by StarJ
main: shining.starj.structure.Core
api-version: 1.20
author: StarJ

commands:
  test:
    description: "테스트"
    usage : "/test"
    operator : admin